<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>form_FullnameEmailPasswordPositionPhoneDesc_57185d</name>
   <tag></tag>
   <elementGuidId>eb3ab835-b549-4bff-8d1a-3d36c9e53c23</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='app']/div/form</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>form</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>form</value>
      <webElementGuid>333ea2bc-0156-4b3b-94bc-cee342cf96f8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>methods</name>
      <type>Main</type>
      <value>POST</value>
      <webElementGuid>47d7c32d-5955-4fef-b93c-61a796fc551c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>FullnameEmailPasswordPositionPhoneDescriptionTypeIndividualCompanyCompany NameEmail CompanyCompany TypeIndustriesAddress I agree to SOCA Master Services Agreement and acknowledge SOCA Privacy Policy. Sign Up </value>
      <webElementGuid>32ecab23-2370-4ee8-bb51-bfd4fa49122a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;app&quot;)/div[@class=&quot;home&quot;]/form[1]</value>
      <webElementGuid>24b8e367-cc2e-4094-87a2-67536e79c13b</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='app']/div/form</value>
      <webElementGuid>8c808269-a9e9-4bed-bcf3-dae6d3cd39f5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Create your account'])[1]/following::form[1]</value>
      <webElementGuid>1841c2aa-265a-42f7-881f-f582351ec2b5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//form</value>
      <webElementGuid>480e7a59-d386-41ca-bba9-2f03c173907c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//form[(text() = 'FullnameEmailPasswordPositionPhoneDescriptionTypeIndividualCompanyCompany NameEmail CompanyCompany TypeIndustriesAddress I agree to SOCA Master Services Agreement and acknowledge SOCA Privacy Policy. Sign Up ' or . = 'FullnameEmailPasswordPositionPhoneDescriptionTypeIndividualCompanyCompany NameEmail CompanyCompany TypeIndustriesAddress I agree to SOCA Master Services Agreement and acknowledge SOCA Privacy Policy. Sign Up ')]</value>
      <webElementGuid>8d7130e0-3062-4004-b4f0-357b9a4a7aa8</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
