<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Email_txt-email</name>
   <tag></tag>
   <elementGuidId>b3df84a7-0254-453a-97d5-02341f6c3023</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#txt-email</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='txt-email']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>99d99630-c1ef-4feb-a0ad-500858db45c0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>email</value>
      <webElementGuid>b9e4e66b-02c5-4d9d-90bb-dce57ab4ef08</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>txt-email</value>
      <webElementGuid>eccce649-b023-44a2-ae78-b0a4ebab3632</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>required</name>
      <type>Main</type>
      <value>required</value>
      <webElementGuid>7d6360de-e71c-41cf-b77a-be6cca58ea5d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control</value>
      <webElementGuid>e482d929-7a87-4ff7-ace9-aaeac1b30900</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;txt-email&quot;)</value>
      <webElementGuid>615fc026-ac95-449f-9ffd-d2015b48ce8b</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='txt-email']</value>
      <webElementGuid>46e738cd-ffeb-41b7-8fc1-69ceb0ccddfd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='app']/div/div[3]/div/div[2]/div/div/div/form/div[2]/div/div/input</value>
      <webElementGuid>84fafce3-3b42-4ca3-aeac-86b99be85826</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div/input</value>
      <webElementGuid>1419165d-a802-4f0e-960d-254b0f07aba2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'email' and @id = 'txt-email']</value>
      <webElementGuid>ee8e009e-052e-4f79-bfac-456aec3278d4</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
