<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>img_1</name>
   <tag></tag>
   <elementGuidId>5a39201b-5a2a-4385-bd25-5899fdcc0717</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='ai-tour-dashboard-3']/div/div/div/div/div/div/img</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>div.position-absolute.ai-img-check-use-case > img</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>85243c45-ba26-4554-92cc-36277e1c0b57</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>https://i.ibb.co/mX4GJkB/Ellipse-1785.png</value>
      <webElementGuid>84e6008b-e05a-424d-ad3d-152c287edb8d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>border</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>6541f568-d77a-4d43-9e14-32ef28eb3ed0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;ai-tour-dashboard-3&quot;)/div[@class=&quot;ai-scroll-horizontal&quot;]/div[@class=&quot;row&quot;]/div[@class=&quot;col-lg-5 col-sm-12 py-1&quot;]/div[@class=&quot;card ai-card-image-opt&quot;]/div[1]/div[@class=&quot;position-absolute ai-img-check-use-case&quot;]/img[1]</value>
      <webElementGuid>503ec745-d353-4b2e-b64a-9670960476f8</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='ai-tour-dashboard-3']/div/div/div/div/div/div/img</value>
      <webElementGuid>09e0a26a-c72f-4d43-a8a6-64530bc476ea</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:img</name>
      <type>Main</type>
      <value>//img[contains(@src,'https://i.ibb.co/mX4GJkB/Ellipse-1785.png')]</value>
      <webElementGuid>45443d79-f9c1-41bc-993d-1433932819a0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/div/div/div/div/div/div/img</value>
      <webElementGuid>d27fb25b-1516-4888-ae67-cd51d626a830</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@src = 'https://i.ibb.co/mX4GJkB/Ellipse-1785.png']</value>
      <webElementGuid>c7ecd32a-ff5e-4999-bca6-c8fe937d3001</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
