<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>img_1</name>
   <tag></tag>
   <elementGuidId>b8f482ad-2da9-4887-8788-4f890897e716</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='ai-tour-dashboard-3']/div/div/div/div/div/div/img</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>div.position-absolute.ai-img-check-use-case > img</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>88385a2d-491e-4a91-ab9a-4d69e36a911f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>https://i.ibb.co/mX4GJkB/Ellipse-1785.png</value>
      <webElementGuid>5ce5c3bd-e937-47c0-b386-c18fb280aff5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>border</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>879f468f-8b57-4522-a302-27bc71a32fa0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;ai-tour-dashboard-3&quot;)/div[@class=&quot;ai-scroll-horizontal&quot;]/div[@class=&quot;row&quot;]/div[@class=&quot;col-lg-5 col-sm-12 py-1&quot;]/div[@class=&quot;card ai-card-image-opt&quot;]/div[1]/div[@class=&quot;position-absolute ai-img-check-use-case&quot;]/img[1]</value>
      <webElementGuid>827c8e0c-40ea-4db0-9672-d7315cdc0516</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='ai-tour-dashboard-3']/div/div/div/div/div/div/img</value>
      <webElementGuid>a4eedfc0-8e17-4256-8cc9-a6acf003c7f9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:img</name>
      <type>Main</type>
      <value>//img[contains(@src,'https://i.ibb.co/mX4GJkB/Ellipse-1785.png')]</value>
      <webElementGuid>8d9b1b2f-15b8-4281-b3ab-0b3762437360</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/div/div/div/div/div/div/img</value>
      <webElementGuid>b18828e3-0958-459e-a6af-a3964b582a8b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@src = 'https://i.ibb.co/mX4GJkB/Ellipse-1785.png']</value>
      <webElementGuid>c6a2279f-0383-4a68-8f9d-8ce26c30330a</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
