<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>img</name>
   <tag></tag>
   <elementGuidId>62417ed7-346c-47a2-9b7c-d220470e4969</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='ai-tour-dashboard-2']/div/div/div/div/img</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>div.position-absolute.ai-img-check-type > img</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>7fed6672-56ec-478d-81a0-f3aa13f5d3c0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>https://i.ibb.co/x53zWwT/Ellipse-1782.png</value>
      <webElementGuid>affd35f7-4522-4711-b967-3200750008ea</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>border</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>91c82f8e-4ff6-4ac9-9d13-79d79c1d253a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;ai-tour-dashboard-2&quot;)/div[@class=&quot;row&quot;]/div[@class=&quot;col-lg-5 col-sm-12&quot;]/div[@class=&quot;card ai-card-opt&quot;]/div[@class=&quot;position-absolute ai-img-check-type&quot;]/img[1]</value>
      <webElementGuid>a80dcc39-8b56-48f7-9e7f-07e796748ad2</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='ai-tour-dashboard-2']/div/div/div/div/img</value>
      <webElementGuid>b7fc6f93-4af9-4e3e-a10b-b37e6dd7b31f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:img</name>
      <type>Main</type>
      <value>//img[contains(@src,'https://i.ibb.co/x53zWwT/Ellipse-1782.png')]</value>
      <webElementGuid>cd74bf52-77f0-4a21-90ea-63108a0fe3a9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/img</value>
      <webElementGuid>5e1f666c-8fb0-430f-bf40-da538f9a7b77</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@src = 'https://i.ibb.co/x53zWwT/Ellipse-1782.png']</value>
      <webElementGuid>d08da391-17c7-4d9b-a841-955c8ffbc25b</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
