<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>img_1</name>
   <tag></tag>
   <elementGuidId>9e3d5db0-509f-40db-869e-2569e3b857e5</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='ai-tour-dashboard-3']/div/div/div/div/div/div/img</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>div.position-absolute.ai-img-check-use-case > img</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>bad828dc-f205-45c9-89f6-1b700c25a5c2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>https://i.ibb.co/mX4GJkB/Ellipse-1785.png</value>
      <webElementGuid>812b4388-cdaf-4e0a-a320-6a8e417a9710</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>border</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>6164e8c7-0a20-4027-a44f-5d69bf1ced4a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;ai-tour-dashboard-3&quot;)/div[@class=&quot;ai-scroll-horizontal&quot;]/div[@class=&quot;row&quot;]/div[@class=&quot;col-lg-5 col-sm-12 py-1&quot;]/div[@class=&quot;card ai-card-image-opt&quot;]/div[1]/div[@class=&quot;position-absolute ai-img-check-use-case&quot;]/img[1]</value>
      <webElementGuid>fe1689d1-6a29-48f6-ac22-513d3a5902d8</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='ai-tour-dashboard-3']/div/div/div/div/div/div/img</value>
      <webElementGuid>c99e2dee-8bb2-4896-9ba3-feec328527ba</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:img</name>
      <type>Main</type>
      <value>//img[contains(@src,'https://i.ibb.co/mX4GJkB/Ellipse-1785.png')]</value>
      <webElementGuid>e57bdab5-c130-423e-888d-02a46b6efbae</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/div/div/div/div/div/div/img</value>
      <webElementGuid>2762ed00-3ea4-482e-b990-38540df3f236</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@src = 'https://i.ibb.co/mX4GJkB/Ellipse-1785.png']</value>
      <webElementGuid>ede9f928-3c5f-491e-a3c4-2121d652a82c</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
