<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Face Recognition_face_regonition</name>
   <tag></tag>
   <elementGuidId>b90f2ef8-61d0-4dc9-a5dd-8639da28a617</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>(//input[@id='faceRegonition'])[3]</value>
      </entry>
      <entry>
         <key>CSS</key>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>272964b0-1843-47c3-97f1-c1f169c8940b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>checkbox</value>
      <webElementGuid>802f058b-5417-47cd-bca9-f4afa615edc3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>face_regonition</value>
      <webElementGuid>8aa4c164-fb85-4598-8687-2ed3af31e783</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>faceRegonition</value>
      <webElementGuid>fa4aab4e-276a-4ab2-bb20-94290e4494af</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-check-input ai-form-checkbox</value>
      <webElementGuid>99a24b88-f919-4cb1-9909-1078d7b5c66e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>4b736010-113c-4d4d-a7c0-69a82914d082</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;accordion-service&quot;)/div[@class=&quot;card-body p-1&quot;]/div[@class=&quot;form-group mb-2&quot;]/div[@class=&quot;form-check ai-form-check mr-2&quot;]/input[@id=&quot;faceRegonition&quot;]</value>
      <webElementGuid>f1065e49-c40d-4309-b4bd-39d0cb26d2cc</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>(//input[@id='faceRegonition'])[3]</value>
      <webElementGuid>6114d0b8-4e0e-4d4c-839f-94b0a22f07c1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='accordion-service']/div/div[3]/div/input</value>
      <webElementGuid>a0776d43-1340-424f-bc5c-a0c98c308aba</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div/input</value>
      <webElementGuid>ecd9b5ab-fd4c-43c1-9bd8-901d7ebcc077</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'checkbox' and @name = 'face_regonition' and @id = 'faceRegonition']</value>
      <webElementGuid>1e743969-4fcf-47be-a7e6-6aa119bb9645</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
