<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Movement Detection_face_regonition</name>
   <tag></tag>
   <elementGuidId>86255869-3468-47c0-9996-214951c57f9e</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>(//input[@id='faceRegonition'])[2]</value>
      </entry>
      <entry>
         <key>CSS</key>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>fcb5aab7-e18c-4021-a3dc-9c30d70fb792</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>checkbox</value>
      <webElementGuid>c7b49d62-00f8-4265-9a15-6047a77c439b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>face_regonition</value>
      <webElementGuid>9f33d4df-4f18-4043-ae71-b5165d79fddc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>faceRegonition</value>
      <webElementGuid>7339cc65-1e97-48ad-814d-fdf090932f23</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-check-input ai-form-checkbox</value>
      <webElementGuid>a1c597c1-4f93-4ecc-8e7e-1e7fffa07ff5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>519ea604-e498-4da7-9209-e88118630a4f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;accordion-service&quot;)/div[@class=&quot;card-body p-1&quot;]/div[@class=&quot;form-group mb-2&quot;]/div[@class=&quot;form-check ai-form-check mr-2&quot;]/input[@id=&quot;faceRegonition&quot;]</value>
      <webElementGuid>24f34d08-06d9-4d7a-b5d5-68841ebc7fce</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>(//input[@id='faceRegonition'])[2]</value>
      <webElementGuid>59f6a1ea-0012-4514-9053-d5938dd2ef0b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='accordion-service']/div/div[2]/div/input</value>
      <webElementGuid>425db919-3d86-43f5-a28e-e9937d54470b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/input</value>
      <webElementGuid>48762e39-2d85-483d-a01b-0028d1a70b92</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'checkbox' and @name = 'face_regonition' and @id = 'faceRegonition']</value>
      <webElementGuid>b8fdea71-3f82-4fdd-90d1-4fbcf9095b78</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
