<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Exam Number_txt-exam-number</name>
   <tag></tag>
   <elementGuidId>46e1c2d2-7a18-44c0-9515-65d4e9259f35</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#txt-exam-number</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='txt-exam-number']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>113383bc-9586-4863-9e14-52f439aedec2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>91baeb79-9eac-482a-b34b-6e3b971a6bf2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>txt-exam-number</value>
      <webElementGuid>9d8abdf4-843b-4d5a-b88f-397a3f4383c6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>required</name>
      <type>Main</type>
      <value>required</value>
      <webElementGuid>c57e09a5-779b-41b6-a3ca-76d5d0d92cf9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control</value>
      <webElementGuid>2607d4df-f68f-437c-85c3-0e98d3b155cd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;txt-exam-number&quot;)</value>
      <webElementGuid>83831a71-41c9-4c14-822e-5fe1106d5264</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='txt-exam-number']</value>
      <webElementGuid>228fc0c4-d4b9-4dfc-996a-bb4ed613190e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='app']/div/div[3]/div/div[2]/div/div/div/form/div[3]/div/div/input</value>
      <webElementGuid>79464355-90ec-46f0-bfe5-755a79861718</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div/div/input</value>
      <webElementGuid>0a811c98-7134-4438-83a8-ff94c0868d38</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @id = 'txt-exam-number']</value>
      <webElementGuid>4d67d489-9b79-4804-bed0-101edabe446d</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
