<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_scheduleSchedule</name>
   <tag></tag>
   <elementGuidId>e8a5c041-9a50-410d-b73d-49a665bc3449</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='app']/div/div/div/div/div[4]/a</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>bd119084-7d2e-4cad-ac04-f72a4e3649ef</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>/auth_key/eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJhdXRob3JpemVkIjp0cnVlLCJleHAiOjc1NTkyNjk4OSwicHJvamVjdHNfaWQiOiIwZDllMmYwZC03ODhjLTRkNGYtNTE3Zi0yNjgxYTVhNGJhN2UifQ.Kt-2qQgAIFs9jIwLXbZ-b2eoeedtMYYVolq2OQVXcYQ/schedule</value>
      <webElementGuid>1af849d9-bcf9-42e9-9817-cca147d34542</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>scheduleSchedule</value>
      <webElementGuid>b76eda9c-dfc8-4e59-9c27-24ff3d0d3436</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;app&quot;)/div[@class=&quot;main-wrapper&quot;]/div[@class=&quot;vs-content-sidebar sidebarx&quot;]/div[@class=&quot;vs-sidebar vs-sidebar-primary vs-sidebar-parent&quot;]/div[@class=&quot;vs-sidebar--items&quot;]/div[@class=&quot;vs-sidebar--item&quot;]/a[1]</value>
      <webElementGuid>6daf29c4-4e17-4778-bc85-b1555289b4a1</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='app']/div/div/div/div/div[4]/a</value>
      <webElementGuid>0c9f5297-991a-4805-bcda-68aa997b806a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Master Event'])[1]/following::a[1]</value>
      <webElementGuid>121de0ba-3ae9-4d15-9817-72150fb80495</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='event'])[1]/following::a[1]</value>
      <webElementGuid>f68b3718-7a91-4f9e-a0e6-d679a3bbe351</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, '/auth_key/eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJhdXRob3JpemVkIjp0cnVlLCJleHAiOjc1NTkyNjk4OSwicHJvamVjdHNfaWQiOiIwZDllMmYwZC03ODhjLTRkNGYtNTE3Zi0yNjgxYTVhNGJhN2UifQ.Kt-2qQgAIFs9jIwLXbZ-b2eoeedtMYYVolq2OQVXcYQ/schedule')]</value>
      <webElementGuid>2f7254ce-2a62-4f52-b391-06719b339a77</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[4]/a</value>
      <webElementGuid>9cb96d8d-0705-4ee1-afd8-5498c416c9fb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = '/auth_key/eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJhdXRob3JpemVkIjp0cnVlLCJleHAiOjc1NTkyNjk4OSwicHJvamVjdHNfaWQiOiIwZDllMmYwZC03ODhjLTRkNGYtNTE3Zi0yNjgxYTVhNGJhN2UifQ.Kt-2qQgAIFs9jIwLXbZ-b2eoeedtMYYVolq2OQVXcYQ/schedule' and (text() = 'scheduleSchedule' or . = 'scheduleSchedule')]</value>
      <webElementGuid>e01a1c47-fd95-4ef4-b628-1b4a9bd3184a</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
