<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Have not received the email_kode_otp1</name>
   <tag></tag>
   <elementGuidId>62f46307-158c-4c12-bfaf-aa6fd4d1d59f</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='digit-1']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#digit-1</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>78b622fe-66c3-4fe9-95da-73959c978828</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>6ad9b7cd-a764-47e0-90c4-dd6d14e3f7c1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>digit-1</value>
      <webElementGuid>e53b8866-1469-4b81-b147-8993dc7649a3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>kode_otp1</value>
      <webElementGuid>54def086-a3a8-4d3a-b846-b1807b6d2860</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-next</name>
      <type>Main</type>
      <value>digit-2</value>
      <webElementGuid>6bcd85e5-c7b8-45ed-b7b4-d567f54f9162</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>required</name>
      <type>Main</type>
      <value>required</value>
      <webElementGuid>aa7feb42-4671-49ed-9fb8-40307277a0d4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>w-25 form-control text-center py-4 mr-2</value>
      <webElementGuid>a910fa10-08e0-4a38-b5bb-c78b8185d69e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>1</value>
      <webElementGuid>83a036d2-752a-4e21-9510-c3cb4b94d45a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;digit-1&quot;)</value>
      <webElementGuid>822ff97e-0004-4935-8b57-a22ceef44df3</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='digit-1']</value>
      <webElementGuid>50bca3c0-3974-4885-b5d0-7d59ec0f462d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='app']/div/form/div/div/div/div/div/div/input</value>
      <webElementGuid>46f96394-64ec-4b90-9d60-fa48ff89717d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//input</value>
      <webElementGuid>5ec71d45-0295-47e0-b336-be4429e81c17</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @id = 'digit-1' and @name = 'kode_otp1']</value>
      <webElementGuid>cfe30966-1d57-4b7c-bf91-8abe0b5b31e8</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
