<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>label_No date selected_1</name>
   <tag></tag>
   <elementGuidId>5ed2e019-55ea-4c12-b42e-ca9b99c45573</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//label[@id='end_date__value_']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#end_date__value_</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>label</value>
      <webElementGuid>63a27b9e-c6b1-41f0-b473-bbb512673069</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>end_date__value_</value>
      <webElementGuid>9dd27dbe-d007-439d-8a2c-9db8151502c3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>for</name>
      <type>Main</type>
      <value>end_date</value>
      <webElementGuid>a1572a2a-d616-44fc-8221-732d362ac869</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control text-muted</value>
      <webElementGuid>e59fd394-9177-44f5-822c-5db29749778c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>No date selected</value>
      <webElementGuid>0b9a26c7-133a-4b88-89de-c6793c4417c2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;end_date__value_&quot;)</value>
      <webElementGuid>4aad1845-c490-4f07-b442-7a689b1f8760</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//label[@id='end_date__value_']</value>
      <webElementGuid>1db7d64b-5d3f-449f-9bd4-c32c34973be5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='end_date__outer_']/label</value>
      <webElementGuid>07cdd9e3-a203-42a3-94aa-524b2cdb6981</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='End Date'])[1]/following::label[1]</value>
      <webElementGuid>20aab8f0-848d-45c0-9e38-0af1e5b8370f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Wednesday, July 20, 2022'])[1]/following::label[2]</value>
      <webElementGuid>49d4171d-9c19-4114-ba80-d4c6a5d9a2bf</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Start Time'])[1]/preceding::label[1]</value>
      <webElementGuid>0275bf26-57df-497a-94f3-f5e1a17e6d77</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='No time selected'])[1]/preceding::label[2]</value>
      <webElementGuid>f4ece347-9dae-4d3d-8ea8-f7037d8cfc0c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='No date selected']/parent::*</value>
      <webElementGuid>be51bcd2-1067-4a60-8277-670b912904c5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div[2]/div/label</value>
      <webElementGuid>7ccc4057-3245-4a47-84a6-1d20a926f4d5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//label[@id = 'end_date__value_' and (text() = 'No date selected' or . = 'No date selected')]</value>
      <webElementGuid>5c2c59a2-ba6c-4254-9a30-7522d0cb2b75</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
