<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Full Name_txt-full-name</name>
   <tag></tag>
   <elementGuidId>aca1690a-6ed0-4dbc-81c8-ea448045de34</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#txt-full-name</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='txt-full-name']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>9586c674-808a-4980-bfea-b5cbc93da261</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>fdd1b71d-2a04-4667-bcdf-a79c35bfb33b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>txt-full-name</value>
      <webElementGuid>55ca5f73-f908-4830-a74a-21d8b64f5ce0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>required</name>
      <type>Main</type>
      <value>required</value>
      <webElementGuid>c13f7c76-5b32-4ef4-9032-ea56c3a848eb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control</value>
      <webElementGuid>7f83cdb9-dabc-485e-a431-6aa7bda1a49a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;txt-full-name&quot;)</value>
      <webElementGuid>014a1b68-c5aa-495f-8373-f612f348f6c1</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='txt-full-name']</value>
      <webElementGuid>fefbeba9-2ac6-4043-8bbc-decbd1e3b3da</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='app']/div/div[3]/div/div[2]/div/div/div/form/div/div[2]/div/input</value>
      <webElementGuid>bb20d082-a016-47a0-bf8c-f94eb7450aed</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/input</value>
      <webElementGuid>de0667d4-c330-4879-90db-0985891f8693</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @id = 'txt-full-name']</value>
      <webElementGuid>39f1baef-6973-42d4-84da-2f30a2480994</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
