<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>label_Wednesday, July 19, 2000</name>
   <tag></tag>
   <elementGuidId>19be3181-2fba-4115-a71a-6661feeaa767</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#start_date__value_</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//label[@id='start_date__value_']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>label</value>
      <webElementGuid>f8080b05-8599-4643-88dc-0efe37f50c28</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>start_date__value_</value>
      <webElementGuid>64cdcc43-4cac-4d77-84e3-aa6c52297429</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>for</name>
      <type>Main</type>
      <value>start_date</value>
      <webElementGuid>f62f5eda-a91c-4094-b04e-a999bfc54279</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-required</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>6a971351-37a8-45e4-b63a-8563b1299c68</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control</value>
      <webElementGuid>a8a962eb-e4e1-48f0-9efd-7817f72aad22</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Wednesday, July 19, 2000</value>
      <webElementGuid>6d2d66fa-1ae3-4541-b9f0-f7daa61bdc3a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;start_date__value_&quot;)</value>
      <webElementGuid>86339190-1938-4d5f-8a9a-ff3495e29206</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//label[@id='start_date__value_']</value>
      <webElementGuid>0e19bdd1-c5f3-4b16-88a3-6216895aaacc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='start_date__outer_']/label</value>
      <webElementGuid>86c7c0b0-5667-4f12-917f-b31a6beae35f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Birth Date'])[1]/following::label[1]</value>
      <webElementGuid>77de97f5-e7ae-42f4-a1db-ef47fc00176c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Exam Number'])[1]/following::label[2]</value>
      <webElementGuid>bd11b224-043e-41d8-a35b-63f94ec763f6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Address'])[1]/preceding::label[1]</value>
      <webElementGuid>69592616-50a1-4162-a863-c61fcec5ef23</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Submit'])[1]/preceding::label[2]</value>
      <webElementGuid>ab83eeef-b4c9-4f3a-bb08-3e2fc6b5aabc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Wednesday, July 19, 2000']/parent::*</value>
      <webElementGuid>31f922bf-0967-4df1-8223-ece7e773aa01</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div[2]/div/div/label</value>
      <webElementGuid>3c34256a-0636-4558-b519-9370e06b0cc6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//label[@id = 'start_date__value_' and (text() = 'Wednesday, July 19, 2000' or . = 'Wednesday, July 19, 2000')]</value>
      <webElementGuid>bc751104-41e2-4c2f-8c66-9413c55ed8c3</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
