<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Exam Number_txt-exam-number</name>
   <tag></tag>
   <elementGuidId>0bdfb940-d3b3-49ae-a620-80241a3ffd99</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#txt-exam-number</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='txt-exam-number']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>1281b779-f970-450c-bfc4-49259f69628b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>f9021668-902e-4e7f-9b43-5bb825061526</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>txt-exam-number</value>
      <webElementGuid>f364dd61-2fd8-44c9-b243-28736bbb01dd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>required</name>
      <type>Main</type>
      <value>required</value>
      <webElementGuid>9a95f139-5f9c-4984-99de-31887657e648</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control</value>
      <webElementGuid>ffcabb75-dfd2-4eb8-9ff6-6134d2902c46</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;txt-exam-number&quot;)</value>
      <webElementGuid>e7f9fd99-d4d1-413b-9b5f-89a468654dc2</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='txt-exam-number']</value>
      <webElementGuid>a1ee2140-2052-4053-b73a-19bee835d65a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='app']/div/div[3]/div/div[2]/div/div/div/form/div[3]/div/div/input</value>
      <webElementGuid>ff42fdba-b24a-4d42-9ce9-88f5c8a19ef5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div/div/input</value>
      <webElementGuid>9daa088f-be74-4002-b7d6-bdb7ecaa13ff</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @id = 'txt-exam-number']</value>
      <webElementGuid>8f48fa50-c73d-49e1-bd63-c659f52e8def</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
