<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>label_Male</name>
   <tag></tag>
   <elementGuidId>a7b17bef-e782-47ed-94a6-1be6f25d24db</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>label.custom-control-label</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='__BVID__70']/div/label</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>label</value>
      <webElementGuid>fac17262-07ef-4061-a87e-ca8e4a8c27b4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>custom-control-label</value>
      <webElementGuid>57b7dda7-68f7-4240-a6f0-877643e54bbc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>for</name>
      <type>Main</type>
      <value>__BVID__70_BV_option_0</value>
      <webElementGuid>698d7849-d263-476a-8736-eab6ce5e28b2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Male</value>
      <webElementGuid>d5498d09-3b8b-485b-a449-37fe1e7aee05</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;__BVID__70&quot;)/div[@class=&quot;custom-control custom-control-inline custom-radio&quot;]/label[@class=&quot;custom-control-label&quot;]</value>
      <webElementGuid>133c2021-b1b2-400b-a414-c35bdd1c537e</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='__BVID__70']/div/label</value>
      <webElementGuid>de07a7b6-3e25-44e8-9331-ae5b8b54f934</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Gender'])[1]/following::label[1]</value>
      <webElementGuid>42fb156e-85ac-4243-8fb5-58cd331ee1f5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Email'])[1]/following::label[1]</value>
      <webElementGuid>af4a3807-ce35-4457-af68-ec3ccef7aae1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Female'])[1]/preceding::label[1]</value>
      <webElementGuid>a71e5974-d3b9-43b4-8107-3cf97cc1117a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//fieldset/div/div/div/label</value>
      <webElementGuid>55d7e338-de3f-4a62-954c-fb62daa7bd81</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//label[(text() = 'Male' or . = 'Male')]</value>
      <webElementGuid>4fcb6e5d-c709-44f6-8185-c745fb2b2cc7</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
