<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>label_No date selected_1</name>
   <tag></tag>
   <elementGuidId>1bb4c0ae-c5ac-47b7-a76c-13d7b7ecd0ae</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#end_date__value_</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//label[@id='end_date__value_']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>label</value>
      <webElementGuid>0d318d26-db2c-4c60-9af3-72ce509122b6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>end_date__value_</value>
      <webElementGuid>58b9dc5e-d506-4415-8e94-6ef6ebebd0e6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>for</name>
      <type>Main</type>
      <value>end_date</value>
      <webElementGuid>07e94659-819f-401b-8133-98d6429afab4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control text-muted</value>
      <webElementGuid>d41c5319-0337-45a3-8138-f148ab5a91ed</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>No date selected</value>
      <webElementGuid>152b29d6-d84f-4f10-b973-ec325782621d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;end_date__value_&quot;)</value>
      <webElementGuid>2f97fce0-8173-4922-9756-173441927940</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>label</value>
      <webElementGuid>230e416c-c8b9-4a47-86d9-1adca3845581</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>end_date__value_</value>
      <webElementGuid>e24dd4d4-8c6a-4263-9e47-23954e5cc179</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>for</name>
      <type>Main</type>
      <value>end_date</value>
      <webElementGuid>2fb66504-e7b8-455a-96fa-43cdbf11bc3c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control text-muted</value>
      <webElementGuid>f6886004-baad-4bf7-b964-0092f5693a1d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>No date selected</value>
      <webElementGuid>9f405553-b68d-4240-bc3b-f72c2d1513df</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;end_date__value_&quot;)</value>
      <webElementGuid>496e2dde-5820-4181-8c19-418e0c26f087</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//label[@id='end_date__value_']</value>
      <webElementGuid>873f873a-4232-43b5-bd1f-011d80537775</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='end_date__outer_']/label</value>
      <webElementGuid>5f57e5ef-3302-431b-ac6e-62ee4169e259</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='End Date'])[1]/following::label[1]</value>
      <webElementGuid>c7d8f86a-7985-462a-98f7-fe089978e349</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Thursday, July 21, 2022'])[1]/following::label[2]</value>
      <webElementGuid>84e14bad-de8a-4c3e-9f09-5f5ad2017089</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Start Time'])[1]/preceding::label[1]</value>
      <webElementGuid>a4192fc8-5402-4464-9ded-cb81f578d7eb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='No time selected'])[1]/preceding::label[2]</value>
      <webElementGuid>a4679003-5d9c-491e-a308-dd01d8dc6e30</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='No date selected']/parent::*</value>
      <webElementGuid>92f663fc-64f1-4749-9d78-60de5073c51a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div[2]/div/label</value>
      <webElementGuid>beb82341-f1a2-4540-bd14-3848600b7d41</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//label[@id = 'end_date__value_' and (text() = 'No date selected' or . = 'No date selected')]</value>
      <webElementGuid>a76808d8-df8c-4e8f-a411-41fa39d75a61</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Wednesday, July 20, 2022'])[1]/following::label[2]</value>
      <webElementGuid>7627d6f3-3fcc-4718-b9e5-b59c1144e288</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
