<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_New Project</name>
   <tag></tag>
   <elementGuidId>b1f6650d-59d1-483f-b543-dfd0b61234b7</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//button[@id='ai-tour-dashboard-1']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#ai-tour-dashboard-1</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>a2cf004b-4911-4743-8cae-c5360f2c12ee</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>ai-tour-dashboard-1</value>
      <webElementGuid>58e78373-3de0-44d6-9589-b96248d91141</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>btn btn-primary btn-new-project</value>
      <webElementGuid>2504d92d-1df4-48b6-9e02-6eec7915563e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value> New Project </value>
      <webElementGuid>6f77b0d1-c428-496d-857c-bbbfce9307e4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;ai-tour-dashboard-1&quot;)</value>
      <webElementGuid>0efb459f-6bee-4913-b8d8-0365de870fc6</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//button[@id='ai-tour-dashboard-1']</value>
      <webElementGuid>be3a42d3-743a-4a32-a81c-c38c41f0be7f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='app']/div/div/div/div/div/div/div/div[2]/div/div/div/div/div[2]/button</value>
      <webElementGuid>7c55771e-bf86-4980-b707-b20247b8d68a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Manage Projects'])[1]/following::button[1]</value>
      <webElementGuid>de19bf83-199b-43de-90c8-edcfb7631a57</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='No'])[1]/preceding::button[1]</value>
      <webElementGuid>40354246-3928-42b5-b31d-f1b8d86be15d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='(Click to sort Descending)'])[1]/preceding::button[1]</value>
      <webElementGuid>d13ef94d-d24b-43ac-9e7b-3e958e655737</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='New Project']/parent::*</value>
      <webElementGuid>b49e3917-5417-4110-b959-12b4361c58b9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/button</value>
      <webElementGuid>e100d5c2-647c-4222-9af9-a6483575fc81</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@id = 'ai-tour-dashboard-1' and (text() = ' New Project ' or . = ' New Project ')]</value>
      <webElementGuid>1041c3da-7720-4099-add4-850dcb3ad18b</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
