<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_All Features_face_regonition</name>
   <tag></tag>
   <elementGuidId>6c37f93b-2733-4566-b05e-e91580cff8f1</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='faceRegonition']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#faceRegonition</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>2bee8078-f27b-4afd-abc8-16d6c01cfdee</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>checkbox</value>
      <webElementGuid>0f9f146c-f68d-4ae3-abfa-1757e967bf2a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>face_regonition</value>
      <webElementGuid>6d6e8829-5ae2-4a4c-af9c-2218166d2012</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>faceRegonition</value>
      <webElementGuid>c1ef19ae-3e28-4339-80c9-3b59a3f73dfa</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-check-input ai-form-checkbox</value>
      <webElementGuid>9c0944cf-3f7d-41af-935d-2f8b15f3f465</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>d858cb75-d545-4825-9daa-58d084bedca2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;accordion-service&quot;)/div[@class=&quot;card-body p-1&quot;]/div[@class=&quot;form-group mb-2&quot;]/div[@class=&quot;form-check ai-form-check mr-2&quot;]/input[@id=&quot;faceRegonition&quot;]</value>
      <webElementGuid>1dbcaadb-2604-40d8-99e4-6204ea77f9be</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='faceRegonition']</value>
      <webElementGuid>d3c24ac3-1ac2-4e84-88e0-d1d241d410cd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='accordion-service']/div/div/div/input</value>
      <webElementGuid>e1adb1af-df36-44c4-832b-4bd013d88e22</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/div/input</value>
      <webElementGuid>11a9795a-7d71-4627-99fe-afdfe0213a69</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'checkbox' and @name = 'face_regonition' and @id = 'faceRegonition']</value>
      <webElementGuid>b350759f-11cb-438b-ba56-2db4d7b81ab6</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
