<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_API Transaction_txt-api-transaction</name>
   <tag></tag>
   <elementGuidId>4bea7228-67e9-4e89-b89e-26e61c60262f</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='txt-api-transaction']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#txt-api-transaction</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>c1d3d2c0-caf6-412f-a270-7105eaa4500a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>number</value>
      <webElementGuid>ddb6a839-a603-4753-8d98-1321de345ff7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>txt-api-transaction</value>
      <webElementGuid>e1da4efd-5682-44ab-8fb2-5fa98eb40330</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>1000</value>
      <webElementGuid>66d0c25f-f478-4765-a8c7-bc406da3bb35</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>max</name>
      <type>Main</type>
      <value>10000</value>
      <webElementGuid>91e1cc91-6d5b-49f0-81b6-2e102d8762fc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control</value>
      <webElementGuid>924d3878-9681-4576-a9e3-60e1ec0eccea</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;txt-api-transaction&quot;)</value>
      <webElementGuid>cd9541f5-df45-413a-8db7-abbded282255</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='txt-api-transaction']</value>
      <webElementGuid>5e29a2ab-93f0-4b2a-85fd-bc708290e2dc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='ai-tour-dashboard-4']/input</value>
      <webElementGuid>7933984d-46f4-4dda-b18d-b03993fdd959</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//span/div/input</value>
      <webElementGuid>dd329c4e-373d-48aa-af2c-5691bbc2685d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'number' and @id = 'txt-api-transaction' and @placeholder = '1000']</value>
      <webElementGuid>20c8cc6c-10c0-4781-9c4f-b2a4460eec32</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
